"""Начальная схема ядра СКАЙПАРК (pgvector, посещения, оплаты, уведомления).

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 15:17:07.980973
"""

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('applies_to', sa.String(length=16), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint("applies_to in ('any', 'visit', 'extension')", name='ck_discounts_applies_to'),
    sa.CheckConstraint("type in ('percent', 'fixed')", name='ck_discounts_type'),
    sa.CheckConstraint('value > 0', name='ck_discounts_value'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duration_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("kind in ('visit', 'extension')", name='ck_duration_options_kind'),
    sa.CheckConstraint('minutes > 0', name='ck_duration_options_minutes'),
    sa.CheckConstraint('price >= 0', name='ck_duration_options_price'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=64), nullable=True),
    sa.Column('telegram_linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('telegram_chat_id')
    )
    op.create_table('promo_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('applies_to', sa.String(length=16), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_parent', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("applies_to in ('any', 'visit', 'extension')", name='ck_promo_codes_applies_to'),
    sa.CheckConstraint("type in ('percent', 'fixed')", name='ck_promo_codes_type'),
    sa.CheckConstraint('value > 0', name='ck_promo_codes_value'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('schedule_exceptions',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.CheckConstraint('is_closed or (opens_at is not null and closes_at is not null and closes_at > opens_at)', name='ck_schedule_exceptions_hours'),
    sa.PrimaryKeyConstraint('day')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('position', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role in ('admin', 'employee', 'nanny')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('work_schedule',
    sa.Column('weekday', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.Column('is_day_off', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('closes_at > opens_at', name='ck_work_schedule_hours'),
    sa.CheckConstraint('weekday between 0 and 6', name='ck_work_schedule_weekday'),
    sa.PrimaryKeyConstraint('weekday')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=8), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender is null or gender in ('male', 'female')", name='ck_children_gender'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_children_parent_id'), 'children', ['parent_id'], unique=False)
    op.create_table('nannies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('max_children', sa.Integer(), nullable=False),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('started_work_on', sa.Date(), nullable=True),
    sa.CheckConstraint("status in ('working', 'break', 'off')", name='ck_nannies_status'),
    sa.CheckConstraint('max_children > 0', name='ck_nannies_max_children'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('face_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=False),
    sa.Column('det_score', sa.Float(), nullable=False),
    sa.Column('thumbnail', sa.LargeBinary(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_profiles_child_id'), 'face_profiles', ['child_id'], unique=False)
    op.create_index('ix_face_profiles_hnsw', 'face_profiles', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('nanny_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('base_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.String(length=16), nullable=True),
    sa.Column('reminder_sent_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extension_declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("end_reason is null or end_reason in ('manual', 'auto', 'cancelled')", name='ck_visits_end_reason'),
    sa.CheckConstraint("status in ('created', 'active', 'awaiting_extension', 'extended', 'completed', 'cancelled')", name='ck_visits_status'),
    sa.CheckConstraint('ended_at is null or ended_at >= started_at', name='ck_visits_ended_at'),
    sa.CheckConstraint('planned_end_at > started_at', name='ck_visits_planned_end'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nanny_id'], ['nannies.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['duration_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_child_id'), 'visits', ['child_id'], unique=False)
    op.create_index(op.f('ix_visits_nanny_id'), 'visits', ['nanny_id'], unique=False)
    op.create_index('ix_visits_status_planned_end', 'visits', ['status', 'planned_end_at'], unique=False)
    op.create_index('uq_visits_one_open_per_child', 'visits', ['child_id'], unique=True, postgresql_where=sa.text("status in ('created', 'active', 'awaiting_extension', 'extended')"))
    op.create_table('extensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('requested_by', sa.String(length=16), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("requested_by in ('parent', 'staff')", name='ck_extensions_requested_by'),
    sa.CheckConstraint("status in ('pending_payment', 'applied', 'failed', 'cancelled')", name='ck_extensions_status'),
    sa.ForeignKeyConstraint(['option_id'], ['duration_options.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extensions_visit_id'), 'extensions', ['visit_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('visit_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("channel in ('telegram', 'web')", name='ck_notifications_channel'),
    sa.CheckConstraint("status in ('pending', 'sent', 'failed', 'skipped')", name='ck_notifications_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_key')
    )
    op.create_index(op.f('ix_notifications_parent_id'), 'notifications', ['parent_id'], unique=False)
    op.create_index('ix_notifications_queue', 'notifications', ['channel', 'status', 'next_attempt_at'], unique=False)
    op.create_index(op.f('ix_notifications_visit_id'), 'notifications', ['visit_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('extension_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=128), nullable=True),
    sa.Column('pay_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=True),
    sa.Column('promo_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'extension') = (extension_id is not null)", name='ck_payments_extension'),
    sa.CheckConstraint("kind in ('visit', 'extension')", name='ck_payments_kind'),
    sa.CheckConstraint("method in ('offline', 'online')", name='ck_payments_method'),
    sa.CheckConstraint("status in ('created', 'pending', 'paid', 'failed', 'cancelled', 'refunded')", name='ck_payments_status'),
    sa.CheckConstraint('amount >= 0', name='ck_payments_amount'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ),
    sa.ForeignKeyConstraint(['extension_id'], ['extensions.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extension_id')
    )
    op.create_index('ix_payments_provider_id', 'payments', ['provider', 'provider_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_visit_id'), 'payments', ['visit_id'], unique=False)
    op.create_table('promo_code_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promo_code_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.create_index(op.f('ix_promo_code_usages_parent_id'), 'promo_code_usages', ['parent_id'], unique=False)
    op.create_index(op.f('ix_promo_code_usages_promo_code_id'), 'promo_code_usages', ['promo_code_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promo_code_usages_promo_code_id'), table_name='promo_code_usages')
    op.drop_index(op.f('ix_promo_code_usages_parent_id'), table_name='promo_code_usages')
    op.drop_table('promo_code_usages')
    op.drop_index(op.f('ix_payments_visit_id'), table_name='payments')
    op.drop_index('ix_payments_provider_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_notifications_visit_id'), table_name='notifications')
    op.drop_index('ix_notifications_queue', table_name='notifications')
    op.drop_index(op.f('ix_notifications_parent_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_extensions_visit_id'), table_name='extensions')
    op.drop_table('extensions')
    op.drop_index('uq_visits_one_open_per_child', table_name='visits', postgresql_where=sa.text("status in ('created', 'active', 'awaiting_extension', 'extended')"))
    op.drop_index('ix_visits_status_planned_end', table_name='visits')
    op.drop_index(op.f('ix_visits_nanny_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_child_id'), table_name='visits')
    op.drop_table('visits')
    op.drop_index('ix_face_profiles_hnsw', table_name='face_profiles', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_face_profiles_child_id'), table_name='face_profiles')
    op.drop_table('face_profiles')
    op.drop_table('nannies')
    op.drop_index(op.f('ix_children_parent_id'), table_name='children')
    op.drop_table('children')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('work_schedule')
    op.drop_table('users')
    op.drop_table('schedule_exceptions')
    op.drop_table('promo_codes')
    op.drop_table('parents')
    op.drop_table('duration_options')
    op.drop_table('discounts')
    # ### end Alembic commands ###
